language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

deploy:
  provider: releases
  user: "792626757@qq.com"
  password: "tc3141526github"
  file:
    - "build/apk/android-tdd-playground-debug-test-unaligned.apk"
    - "build/apk/android-tdd-playground-debug-unaligned.apk"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - cd build
  - tree
  - cd apk
  - ls
